In [2]:
import pandas as pd

In [4]:
path = r"/home/davicruvel/airflow_project/data/raw/fruits/fruit-main/Apples-2022.xlsx"
df = pd.read_excel(path)
df.head(3)

,"Apples—Average retail price per pound or pint and per cup equivalent, 2022",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Form,Average retail price,NaN,Preparation yield factor,Size of a cup equivalent,NaN,Average price per cup equivalent
1,Fresh1,1.854107,per pound,0.9,0.242508,Pounds,0.499596
2,Applesauce2,1.170549,per pound,1,0.540133,Pounds,0.632252

In [5]:
xls = pd.ExcelFile(path)

# Carregar a aba "Apples" ignorando a primeira linha
df_apples_clean = pd.read_excel(xls, sheet_name="Apples", skiprows=1)

# Remover linhas que contêm notas explicativas (detectadas por presença de palavras-chave)
df_apples_clean = df_apples_clean[~df_apples_clean.iloc[:, 0].astype(str).str.contains("USDA|Source|Excludes|Includes", na=False)]

# Resetar o índice após limpeza
df_apples_clean.reset_index(drop=True, inplace=True)

# Renomear colunas para facilitar a interpretação
df_apples_clean.columns = [
    "Category", "Avg_Retail_Price", "Unit", "Prep_Yield_Factor", 
    "Cup_Size", "Cup_Unit", "Avg_Price_Cup"
]

# Exibir as primeiras linhas após a limpeza
df_apples_clean.head(10)

,Category,Avg_Retail_Price,Unit,Prep_Yield_Factor,Cup_Size,Cup_Unit,Avg_Price_Cup
0,Fresh1,1.854107,per pound,0.9,0.242508,Pounds,0.499596
1,Applesauce2,1.170549,per pound,1.0,0.540133,Pounds,0.632252
2,Juice,NaN,NaN,NaN,NaN,NaN,NaN
3,Ready to drink3,0.869853,per pint,1.0,8.000000,Fluid ounces,0.434926
4,Frozen4,0.608641,per pint,1.0,8.000000,Fluid ounces,0.304321